// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

using Microsoft.EntityFrameworkCore;

namespace Minimal_API.Models;

public partial class minimalApiContext : DbContext
{
    public minimalApiContext(DbContextOptions<minimalApiContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Administrador> Administrador { get; set; }

    public virtual DbSet<Veiculo> Veiculo { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Administrador>(entity =>
        {
            entity.HasKey(a => a.Id);

            // Definir que o Id será auto incrementado
            entity.Property(a => a.Id)
                  .ValueGeneratedOnAdd(); // Auto incremento (Identity)

            // Configurar a propriedade Email
            entity.Property(a => a.Email)
                  .IsRequired() // Torna o campo obrigatório
                  .HasMaxLength(255); // Define o tamanho máximo para a coluna

            // Configurar a propriedade Senha
            entity.Property(a => a.Senha)
                  .IsRequired() // Torna o campo obrigatório
                  .HasMaxLength(50); // Define o tamanho máximo para a coluna

            // Configurar a propriedade Perfil
            entity.Property(a => a.Perfil)
                  .IsRequired() // Torna o campo obrigatório
                  .HasMaxLength(10); // Define o tamanho máximo para a coluna
        });

        modelBuilder.Entity<Veiculo>(entity =>
        {
            // Definir a chave primária
            entity.HasKey(v => v.Id);

            // Definir que o Id será auto incrementado
            entity.Property(v => v.Id)
                  .ValueGeneratedOnAdd(); // Auto incremento (Identity)

            // Configurar a propriedade Nome
            entity.Property(v => v.Nome)
                  .IsRequired()  // Torna o campo obrigatório
                  .HasMaxLength(150); // Define o tamanho máximo para a coluna

            // Configurar a propriedade Marca
            entity.Property(v => v.Marca)
                  .IsRequired() // Torna o campo obrigatório
                  .HasMaxLength(100); // Define o tamanho máximo para a coluna

            // Configurar a propriedade Ano
            entity.Property(v => v.Ano)
                  .IsRequired(); // Torna o campo obrigatório
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}